from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('login/',views.login,name='login'),
    path('logcode/',views.logcode,name='logcode'),
    path('adminlayout/',views.adminlayout,name='adminlayout'),
    path('showenquiry/',views.showenq,name='showenq'),
    path('addsession/',views.addsession,name='addsession'),
    path('assave/',views.assave,name='assave'),
    path('showsession',views.showsession,name='showsession'), 
    path('addcourse/',views.addcourse,name='addcourse'),
    path('deltbl<id>',views.deltbl,name='deltbl'),
    path('showcourse/',views.showcourse,name='showcourse'),
    path('coldel<id>',views.coldel,name='coldel'),
    path('editsession/',views.editsession,name='editsession'),
    path('editsession<id>',views.editsession,name='editsession'),
    path('updatedata',views.updatedata,name='updatedata'),
    path('addstudent/',views.addstudent,name='addstudent'),
    path('studentdash/',views.studentdash,name='studentdash'),
    path('application/',views.application,name='application'),
    path('saveinfo/',views.saveinfo,name='saveinfo'),
    path('showstudent/',views.showstudent,name='showstudent'),
    path('uploaddoc/',views.uploaddoc,name='uploaddoc'),
    path('verifydoc/',views.verifydoc,name='verifydoc'),
    path('admindash/',views.admindash,name='admindash'),
    path('verifystu/<id>',views.verifystu,name='verifystu'),
    path('payfees/' ,views.payfees,name='payfees'),
    path('finalsubmit/',views.finalsubmit,name='finalsubmit'),
    path('finalverification/',views.finalverification,name='finalverification'),
    path('assign/<id>',views.assign,name='assign'),
    path('finalstudents/',views.finalstudents,name='finalstudents'),
    path('logout/',views.logout,name='logout'),
    path('changepass/',views.changepass,name='changepass'),
    path('changesave/',views.changesave,name='changesave'),
]